
#line 3 "nslexer.c"

#define _nsyywrap _ns_nsyywrap

#define  _NSYY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define _NSYY_FLEX_MAJOR_VERSION 2
#define _NSYY_FLEX_MINOR_VERSION 6
#define _NSYY_FLEX_SUBMINOR_VERSION 4
#if _NSYY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define _nsyyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define _nsyynoreturn __attribute__((__noreturn__))
#else
#define _nsyynoreturn
#endif

/* Returned upon end-of-file. */
#define _NSYY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define _NSYY_SC_TO_UI(c) ((_NSYY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (_nsyy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The _NSYYSTATE alias is for lex
 * compatibility.
 */
#define _NSYY_START (((_nsyy_start) - 1) / 2)
#define _NSYYSTATE _NSYY_START
/* Action number for EOF rule of a given start state. */
#define _NSYY_STATE_EOF(state) (_NSYY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define _NSYY_NEW_FILE _nsyyrestart( _nsyyin  )
#define _NSYY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef _NSYY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, _NSYY_BUF_SIZE is 2*_NSYY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define _NSYY_BUF_SIZE 32768
#else
#define _NSYY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define _NSYY_STATE_BUF_SIZE   ((_NSYY_BUF_SIZE + 2) * sizeof(_nsyy_state_type))

#ifndef _NSYY_TYPEDEF__NSYY_BUFFER_STATE
#define _NSYY_TYPEDEF__NSYY_BUFFER_STATE
typedef struct _nsyy_buffer_state *_NSYY_BUFFER_STATE;
#endif

#ifndef _NSYY_TYPEDEF__NSYY_SIZE_T
#define _NSYY_TYPEDEF__NSYY_SIZE_T
typedef size_t _nsyy_size_t;
#endif

extern int _nsyyleng;

extern FILE *_nsyyin, *_nsyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for _nsyy_rule_can_match_eol because it requires
     *       access to the local variable _nsyy_act. Since _nsyyless() is a macro, it would break
     *       existing scanners that call _nsyyless() from OUTSIDE _nsyylex.
     *       One obvious solution it to make _nsyy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-_nsyylineno scanner, because _nsyy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  _NSYY_LESS_LINENO(n) \
            do { \
                int _nsyyl;\
                for ( _nsyyl = n; _nsyyl < _nsyyleng; ++_nsyyl )\
                    if ( _nsyytext[_nsyyl] == '\n' )\
                        --_nsyylineno;\
            }while(0)
    #define _NSYY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = _nsyy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --_nsyylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define _nsyyless(n) \
	do \
		{ \
		/* Undo effects of setting up _nsyytext. */ \
        int _nsyyless_macro_arg = (n); \
        _NSYY_LESS_LINENO(_nsyyless_macro_arg);\
		*_nsyy_cp = (_nsyy_hold_char); \
		_NSYY_RESTORE__NSYY_MORE_OFFSET \
		(_nsyy_c_buf_p) = _nsyy_cp = _nsyy_bp + _nsyyless_macro_arg - _NSYY_MORE_ADJ; \
		_NSYY_DO_BEFORE_ACTION; /* set up _nsyytext again */ \
		} \
	while ( 0 )
#define unput(c) _nsyyunput( c, (_nsyytext_ptr)  )

#ifndef _NSYY_STRUCT__NSYY_BUFFER_STATE
#define _NSYY_STRUCT__NSYY_BUFFER_STATE
struct _nsyy_buffer_state
	{
	FILE *_nsyy_input_file;

	char *_nsyy_ch_buf;		/* input buffer */
	char *_nsyy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int _nsyy_buf_size;

	/* Number of characters read into _nsyy_ch_buf, not including EOB
	 * characters.
	 */
	int _nsyy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int _nsyy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int _nsyy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int _nsyy_at_bol;

    int _nsyy_bs_lineno; /**< The line count. */
    int _nsyy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int _nsyy_fill_buffer;

	int _nsyy_buffer_status;

#define _NSYY_BUFFER_NEW 0
#define _NSYY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as _NSYY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via _nsyyrestart()), so that the user can continue scanning by
	 * just pointing _nsyyin at a new input file.
	 */
#define _NSYY_BUFFER_EOF_PENDING 2

	};
#endif /* !_NSYY_STRUCT__NSYY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t _nsyy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t _nsyy_buffer_stack_max = 0; /**< capacity of stack. */
static _NSYY_BUFFER_STATE * _nsyy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define _NSYY_CURRENT_BUFFER ( (_nsyy_buffer_stack) \
                          ? (_nsyy_buffer_stack)[(_nsyy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define _NSYY_CURRENT_BUFFER_LVALUE (_nsyy_buffer_stack)[(_nsyy_buffer_stack_top)]

/* _nsyy_hold_char holds the character lost when _nsyytext is formed. */
static char _nsyy_hold_char;
static int _nsyy_n_chars;		/* number of characters read into _nsyy_ch_buf */
int _nsyyleng;

/* Points to current character in buffer. */
static char *_nsyy_c_buf_p = NULL;
static int _nsyy_init = 0;		/* whether we need to initialize */
static int _nsyy_start = 0;	/* start state number */

/* Flag which is used to allow _nsyywrap()'s to do buffer switches
 * instead of setting up a fresh _nsyyin.  A bit of a hack ...
 */
static int _nsyy_did_buffer_switch_on_eof;

void _nsyyrestart ( FILE *input_file  );
void _nsyy_switch_to_buffer ( _NSYY_BUFFER_STATE new_buffer  );
_NSYY_BUFFER_STATE _nsyy_create_buffer ( FILE *file, int size  );
void _nsyy_delete_buffer ( _NSYY_BUFFER_STATE b  );
void _nsyy_flush_buffer ( _NSYY_BUFFER_STATE b  );
void _nsyypush_buffer_state ( _NSYY_BUFFER_STATE new_buffer  );
void _nsyypop_buffer_state ( void );

static void _nsyyensure_buffer_stack ( void );
static void _nsyy_load_buffer_state ( void );
static void _nsyy_init_buffer ( _NSYY_BUFFER_STATE b, FILE *file  );
#define _NSYY_FLUSH_BUFFER _nsyy_flush_buffer( _NSYY_CURRENT_BUFFER )

_NSYY_BUFFER_STATE _nsyy_scan_buffer ( char *base, _nsyy_size_t size  );
_NSYY_BUFFER_STATE _nsyy_scan_string ( const char *_nsyy_str  );
_NSYY_BUFFER_STATE _nsyy_scan_bytes ( const char *bytes, int len  );

void *_nsyyalloc ( _nsyy_size_t  );
void *_nsyyrealloc ( void *, _nsyy_size_t  );
void _nsyyfree ( void *  );

#define _nsyy_new_buffer _nsyy_create_buffer
#define _nsyy_set_interactive(is_interactive) \
	{ \
	if ( ! _NSYY_CURRENT_BUFFER ){ \
        _nsyyensure_buffer_stack (); \
		_NSYY_CURRENT_BUFFER_LVALUE =    \
            _nsyy_create_buffer( _nsyyin, _NSYY_BUF_SIZE ); \
	} \
	_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_is_interactive = is_interactive; \
	}
#define _nsyy_set_bol(at_bol) \
	{ \
	if ( ! _NSYY_CURRENT_BUFFER ){\
        _nsyyensure_buffer_stack (); \
		_NSYY_CURRENT_BUFFER_LVALUE =    \
            _nsyy_create_buffer( _nsyyin, _NSYY_BUF_SIZE ); \
	} \
	_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_at_bol = at_bol; \
	}
#define _NSYY_AT_BOL() (_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t _NSYY_CHAR;

FILE *_nsyyin = NULL, *_nsyyout = NULL;

typedef int _nsyy_state_type;

extern int _nsyylineno;
int _nsyylineno = 1;

extern char *_nsyytext;
#ifdef _nsyytext_ptr
#undef _nsyytext_ptr
#endif
#define _nsyytext_ptr _nsyytext

static _nsyy_state_type _nsyy_get_previous_state ( void );
static _nsyy_state_type _nsyy_try_NUL_trans ( _nsyy_state_type current_state  );
static int _nsyy_get_next_buffer ( void );
static void _nsyynoreturn _nsyy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up _nsyytext.
 */
#define _NSYY_DO_BEFORE_ACTION \
	(_nsyytext_ptr) = _nsyy_bp; \
	_nsyyleng = (int) (_nsyy_cp - _nsyy_bp); \
	(_nsyy_hold_char) = *_nsyy_cp; \
	*_nsyy_cp = '\0'; \
	(_nsyy_c_buf_p) = _nsyy_cp;
#define _NSYY_NUM_RULES 13
#define _NSYY_END_OF_BUFFER 14
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct _nsyy_trans_info
	{
	flex_int32_t _nsyy_verify;
	flex_int32_t _nsyy_nxt;
	};
static const flex_int16_t _nsyy_accept[59] =
    {   0,
        0,    0,   14,   12,    1,    4,    2,   11,   11,   11,
       11,   11,   11,   11,   12,    1,    2,   11,   11,   11,
       11,   11,   11,   11,    3,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,    9,   11,   11,   11,   11,
       11,    5,   11,    6,   10,    7,    8,    0
    } ;

static const _NSYY_CHAR _nsyy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,   10,   11,
       12,    7,   13,    7,    7,   14,    7,   15,   16,    7,
        7,   17,   18,   19,   20,   21,    7,    7,   22,    7,
        1,   23,    1,    1,    5,    1,    6,    7,    8,    9,

       10,   11,   12,    7,   13,    7,    7,   14,    7,   15,
       16,    7,    7,   17,   18,   19,   20,   21,    7,    7,
       22,    7,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const _NSYY_CHAR _nsyy_meta[24] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1
    } ;

static const flex_int16_t _nsyy_base[61] =
    {   0,
        0,    0,   68,   69,   65,   69,    0,    0,   50,   49,
       54,   43,   45,   46,   57,   57,    0,    0,   43,   38,
       37,   47,   32,   47,   69,   33,   40,   30,   41,   42,
       26,   33,   29,   27,   33,   30,   35,   25,   19,   23,
       19,   30,   22,   14,   18,    0,   14,   18,   16,   19,
       19,    0,   12,    0,    0,    0,    0,   69,   23,   22
    } ;

static const flex_int16_t _nsyy_def[61] =
    {   0,
       58,    1,   58,   58,   58,   58,   59,   60,   60,   60,
       60,   60,   60,   60,   58,   58,   59,   60,   60,   60,
       60,   60,   60,   60,   58,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,    0,   58,   58
    } ;

static const flex_int16_t _nsyy_nxt[93] =
    {   0,
        4,    5,    6,    7,    4,    8,    8,    9,    8,    8,
        8,    8,    8,    8,   10,    8,   11,   12,   13,   14,
        8,    8,   15,   17,   18,   17,   57,   56,   55,   54,
       53,   52,   51,   50,   49,   48,   47,   46,   45,   44,
       43,   42,   41,   40,   39,   38,   37,   36,   35,   34,
       33,   32,   31,   30,   29,   28,   27,   26,   16,   25,
       24,   23,   22,   21,   20,   19,   16,   58,    3,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58

    } ;

static const flex_int16_t _nsyy_chk[93] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   59,   60,   59,   53,   51,   50,   49,
       48,   47,   45,   44,   43,   42,   41,   40,   39,   38,
       37,   36,   35,   34,   33,   32,   31,   30,   29,   28,
       27,   26,   24,   23,   22,   21,   20,   19,   16,   15,
       14,   13,   12,   11,   10,    9,    5,    3,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t _nsyy_rule_can_match_eol[14] =
    {   0,
0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static _nsyy_state_type _nsyy_last_accepting_state;
static char *_nsyy_last_accepting_cpos;

extern int _nsyy_flex_debug;
int _nsyy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define _nsyymore() _nsyymore_used_but_not_detected
#define _NSYY_MORE_ADJ 0
#define _NSYY_RESTORE__NSYY_MORE_OFFSET
char *_nsyytext;
#line 1 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
#line 2 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
/*	$NetBSD: nslexer.l,v 1.13 2012/06/25 22:32:45 abs Exp $	*/

/*-
 * Copyright (c) 1997, 1998, 1999 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Luke Mewburn.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <sys/cdefs.h>
#if defined(LIBC_SCCS) && !defined(lint)
__RCSID("$NetBSD: nslexer.l,v 1.13 2012/06/25 22:32:45 abs Exp $");
#endif /* LIBC_SCCS and not lint */

#include "namespace.h"
#include <ctype.h>
#define _NS_PRIVATE
#include <nsswitch.h>
#include <string.h>
//#include <syslog.h>
#include <sys/debug.h>

#include "nsparser.h"

#line 549 "nslexer.c"
#define _NSYY_NO_INPUT 1
#line 551 "nslexer.c"

#define INITIAL 0

#ifndef _NSYY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef _NSYY_EXTRA_TYPE
#define _NSYY_EXTRA_TYPE void *
#endif

static int _nsyy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int _nsyylex_destroy ( void );

int _nsyyget_debug ( void );

void _nsyyset_debug ( int debug_flag  );

_NSYY_EXTRA_TYPE _nsyyget_extra ( void );

void _nsyyset_extra ( _NSYY_EXTRA_TYPE user_defined  );

FILE *_nsyyget_in ( void );

void _nsyyset_in  ( FILE * _in_str  );

FILE *_nsyyget_out ( void );

void _nsyyset_out  ( FILE * _out_str  );

			int _nsyyget_leng ( void );

char *_nsyyget_text ( void );

int _nsyyget_lineno ( void );

void _nsyyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef _NSYY_SKIP__NSYYWRAP
#ifdef __cplusplus
extern "C" int _nsyywrap ( void );
#else
extern int _nsyywrap ( void );
#endif
#endif

#ifndef _NSYY_NO_UNPUT
    
#endif

#ifndef _nsyytext_ptr
static void _nsyy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef _NSYY_NEED_STRLEN
static int _nsyy_flex_strlen ( const char * );
#endif

#ifndef _NSYY_NO_INPUT
#ifdef __cplusplus
static int _nsyyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef _NSYY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define _NSYY_READ_BUF_SIZE 16384
#else
#define _NSYY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( _nsyytext, (size_t) _nsyyleng, 1, _nsyyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or _NSYY_NULL,
 * is returned in "result".
 */
#ifndef _NSYY_INPUT
#define _NSYY_INPUT(buf,result,max_size) \
	if ( _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( _nsyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( _nsyyin ) ) \
			_NSYY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (_nsyy_size_t) max_size, _nsyyin)) == 0 && ferror(_nsyyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				_NSYY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(_nsyyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "_nsyyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef _nsyyterminate
#define _nsyyterminate() return _NSYY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef _NSYY_START_STACK_INCR
#define _NSYY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef _NSYY_FATAL_ERROR
#define _NSYY_FATAL_ERROR(msg) _nsyy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef _NSYY_DECL
#define _NSYY_DECL_IS_OURS 1

extern int _nsyylex (void);

#define _NSYY_DECL int _nsyylex (void)
#endif /* !_NSYY_DECL */

/* Code executed at the beginning of each rule, after _nsyytext and _nsyyleng
 * have been set up.
 */
#ifndef _NSYY_USER_ACTION
#define _NSYY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef _NSYY_BREAK
#define _NSYY_BREAK /*LINTED*/break;
#endif

#define _NSYY_RULE_SETUP \
	_NSYY_USER_ACTION

/** The main scanner function which does all the work.
 */
_NSYY_DECL
{
	_nsyy_state_type _nsyy_current_state;
	char *_nsyy_cp, *_nsyy_bp;
	int _nsyy_act;
    
	if ( !(_nsyy_init) )
		{
		(_nsyy_init) = 1;

#ifdef _NSYY_USER_INIT
		_NSYY_USER_INIT;
#endif

		if ( ! (_nsyy_start) )
			(_nsyy_start) = 1;	/* first start state */

		if ( ! _nsyyin )
			_nsyyin = stdin;

		if ( ! _nsyyout )
			_nsyyout = stdout;

		if ( ! _NSYY_CURRENT_BUFFER ) {
			_nsyyensure_buffer_stack ();
			_NSYY_CURRENT_BUFFER_LVALUE =
				_nsyy_create_buffer( _nsyyin, _NSYY_BUF_SIZE );
		}

		_nsyy_load_buffer_state(  );
		}

	{
#line 57 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"


#line 769 "nslexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		_nsyy_cp = (_nsyy_c_buf_p);

		/* Support of _nsyytext. */
		*_nsyy_cp = (_nsyy_hold_char);

		/* _nsyy_bp points to the position in _nsyy_ch_buf of the start of
		 * the current run.
		 */
		_nsyy_bp = _nsyy_cp;

		_nsyy_current_state = (_nsyy_start);
_nsyy_match:
		do
			{
			_NSYY_CHAR _nsyy_c = _nsyy_ec[_NSYY_SC_TO_UI(*_nsyy_cp)] ;
			if ( _nsyy_accept[_nsyy_current_state] )
				{
				(_nsyy_last_accepting_state) = _nsyy_current_state;
				(_nsyy_last_accepting_cpos) = _nsyy_cp;
				}
			while ( _nsyy_chk[_nsyy_base[_nsyy_current_state] + _nsyy_c] != _nsyy_current_state )
				{
				_nsyy_current_state = (int) _nsyy_def[_nsyy_current_state];
				if ( _nsyy_current_state >= 59 )
					_nsyy_c = _nsyy_meta[_nsyy_c];
				}
			_nsyy_current_state = _nsyy_nxt[_nsyy_base[_nsyy_current_state] + _nsyy_c];
			++_nsyy_cp;
			}
		while ( _nsyy_current_state != 58 );
		_nsyy_cp = (_nsyy_last_accepting_cpos);
		_nsyy_current_state = (_nsyy_last_accepting_state);

_nsyy_find_action:
		_nsyy_act = _nsyy_accept[_nsyy_current_state];

		_NSYY_DO_BEFORE_ACTION;

		if ( _nsyy_act != _NSYY_END_OF_BUFFER && _nsyy_rule_can_match_eol[_nsyy_act] )
			{
			int _nsyyl;
			for ( _nsyyl = 0; _nsyyl < _nsyyleng; ++_nsyyl )
				if ( _nsyytext[_nsyyl] == '\n' )
					
    _nsyylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( _nsyy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of _NSYY_DO_BEFORE_ACTION */
			*_nsyy_cp = (_nsyy_hold_char);
			_nsyy_cp = (_nsyy_last_accepting_cpos);
			_nsyy_current_state = (_nsyy_last_accepting_state);
			goto _nsyy_find_action;

case 1:
_NSYY_RULE_SETUP
#line 59 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
;			/* skip whitespace */
	_NSYY_BREAK
case 2:
_NSYY_RULE_SETUP
#line 61 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
;			/* skip comments */
	_NSYY_BREAK
case 3:
/* rule 3 can match eol */
_NSYY_RULE_SETUP
#line 63 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
;			/* allow continuation */
	_NSYY_BREAK
case 4:
/* rule 4 can match eol */
_NSYY_RULE_SETUP
#line 65 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return NL;
	_NSYY_BREAK
case 5:
_NSYY_RULE_SETUP
#line 67 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return SUCCESS;
	_NSYY_BREAK
case 6:
_NSYY_RULE_SETUP
#line 68 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return UNAVAIL;
	_NSYY_BREAK
case 7:
_NSYY_RULE_SETUP
#line 69 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return NOTFOUND;
	_NSYY_BREAK
case 8:
_NSYY_RULE_SETUP
#line 70 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return TRYAGAIN;
	_NSYY_BREAK
case 9:
_NSYY_RULE_SETUP
#line 72 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return RETURN;
	_NSYY_BREAK
case 10:
_NSYY_RULE_SETUP
#line 73 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return CONTINUE;
	_NSYY_BREAK
case 11:
_NSYY_RULE_SETUP
#line 75 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
{
			char *p;
			size_t i;

			if ((p = strdup(_nsyytext)) == NULL) {
				log_error("libc nsdispatch: %m");
				return NL;
			}

			for (i = 0; i < strlen(p); i++) {
				if (isupper((unsigned char)p[i]))
					p[i] = tolower((unsigned char)p[i]);
			}
//			_ns_nsyylval.str = p;
			_nsyylval.str = p;
			return STRING;
		}
	_NSYY_BREAK
case 12:
_NSYY_RULE_SETUP
#line 93 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
return _nsyytext[0];
	_NSYY_BREAK
case 13:
_NSYY_RULE_SETUP
#line 95 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"
ECHO;
	_NSYY_BREAK
#line 915 "nslexer.c"
case _NSYY_STATE_EOF(INITIAL):
	_nsyyterminate();

	case _NSYY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int _nsyy_amount_of_matched_text = (int) (_nsyy_cp - (_nsyytext_ptr)) - 1;

		/* Undo the effects of _NSYY_DO_BEFORE_ACTION. */
		*_nsyy_cp = (_nsyy_hold_char);
		_NSYY_RESTORE__NSYY_MORE_OFFSET

		if ( _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buffer_status == _NSYY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed _nsyyin at a new source and called
			 * _nsyylex().  If so, then we have to assure
			 * consistency between _NSYY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(_nsyy_n_chars) = _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_n_chars;
			_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_input_file = _nsyyin;
			_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buffer_status = _NSYY_BUFFER_NORMAL;
			}

		/* Note that here we test for _nsyy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since _nsyy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (_nsyy_c_buf_p) <= &_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[(_nsyy_n_chars)] )
			{ /* This was really a NUL. */
			_nsyy_state_type _nsyy_next_state;

			(_nsyy_c_buf_p) = (_nsyytext_ptr) + _nsyy_amount_of_matched_text;

			_nsyy_current_state = _nsyy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * _nsyy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			_nsyy_next_state = _nsyy_try_NUL_trans( _nsyy_current_state );

			_nsyy_bp = (_nsyytext_ptr) + _NSYY_MORE_ADJ;

			if ( _nsyy_next_state )
				{
				/* Consume the NUL. */
				_nsyy_cp = ++(_nsyy_c_buf_p);
				_nsyy_current_state = _nsyy_next_state;
				goto _nsyy_match;
				}

			else
				{
				_nsyy_cp = (_nsyy_last_accepting_cpos);
				_nsyy_current_state = (_nsyy_last_accepting_state);
				goto _nsyy_find_action;
				}
			}

		else switch ( _nsyy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(_nsyy_did_buffer_switch_on_eof) = 0;

				if ( _nsyywrap(  ) )
					{
					/* Note: because we've taken care in
					 * _nsyy_get_next_buffer() to have set up
					 * _nsyytext, we can now set up
					 * _nsyy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * _NSYY_NULL, it'll still work - another
					 * _NSYY_NULL will get returned.
					 */
					(_nsyy_c_buf_p) = (_nsyytext_ptr) + _NSYY_MORE_ADJ;

					_nsyy_act = _NSYY_STATE_EOF(_NSYY_START);
					goto do_action;
					}

				else
					{
					if ( ! (_nsyy_did_buffer_switch_on_eof) )
						_NSYY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(_nsyy_c_buf_p) =
					(_nsyytext_ptr) + _nsyy_amount_of_matched_text;

				_nsyy_current_state = _nsyy_get_previous_state(  );

				_nsyy_cp = (_nsyy_c_buf_p);
				_nsyy_bp = (_nsyytext_ptr) + _NSYY_MORE_ADJ;
				goto _nsyy_match;

			case EOB_ACT_LAST_MATCH:
				(_nsyy_c_buf_p) =
				&_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[(_nsyy_n_chars)];

				_nsyy_current_state = _nsyy_get_previous_state(  );

				_nsyy_cp = (_nsyy_c_buf_p);
				_nsyy_bp = (_nsyytext_ptr) + _NSYY_MORE_ADJ;
				goto _nsyy_find_action;
			}
		break;
		}

	default:
		_NSYY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of _nsyylex */

/* _nsyy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int _nsyy_get_next_buffer (void)
{
    	char *dest = _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf;
	char *source = (_nsyytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (_nsyy_c_buf_p) > &_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[(_nsyy_n_chars) + 1] )
		_NSYY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (_nsyy_c_buf_p) - (_nsyytext_ptr) - _NSYY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((_nsyy_c_buf_p) - (_nsyytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buffer_status == _NSYY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_n_chars = (_nsyy_n_chars) = 0;

	else
		{
			int num_to_read =
			_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			_NSYY_BUFFER_STATE b = _NSYY_CURRENT_BUFFER_LVALUE;

			int _nsyy_c_buf_p_offset =
				(int) ((_nsyy_c_buf_p) - b->_nsyy_ch_buf);

			if ( b->_nsyy_is_our_buffer )
				{
				int new_size = b->_nsyy_buf_size * 2;

				if ( new_size <= 0 )
					b->_nsyy_buf_size += b->_nsyy_buf_size / 8;
				else
					b->_nsyy_buf_size *= 2;

				b->_nsyy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					_nsyyrealloc( (void *) b->_nsyy_ch_buf,
							 (_nsyy_size_t) (b->_nsyy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->_nsyy_ch_buf = NULL;

			if ( ! b->_nsyy_ch_buf )
				_NSYY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(_nsyy_c_buf_p) = &b->_nsyy_ch_buf[_nsyy_c_buf_p_offset];

			num_to_read = _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > _NSYY_READ_BUF_SIZE )
			num_to_read = _NSYY_READ_BUF_SIZE;

		/* Read in more data. */
		_NSYY_INPUT( (&_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[number_to_move]),
			(_nsyy_n_chars), num_to_read );

		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_n_chars = (_nsyy_n_chars);
		}

	if ( (_nsyy_n_chars) == 0 )
		{
		if ( number_to_move == _NSYY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			_nsyyrestart( _nsyyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buffer_status =
				_NSYY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((_nsyy_n_chars) + number_to_move) > _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (_nsyy_n_chars) + number_to_move + ((_nsyy_n_chars) >> 1);
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf = (char *) _nsyyrealloc(
			(void *) _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf, (_nsyy_size_t) new_size  );
		if ( ! _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf )
			_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_size = (int) (new_size - 2);
	}

	(_nsyy_n_chars) += number_to_move;
	_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[(_nsyy_n_chars)] = _NSYY_END_OF_BUFFER_CHAR;
	_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[(_nsyy_n_chars) + 1] = _NSYY_END_OF_BUFFER_CHAR;

	(_nsyytext_ptr) = &_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[0];

	return ret_val;
}

/* _nsyy_get_previous_state - get the state just before the EOB char was reached */

    static _nsyy_state_type _nsyy_get_previous_state (void)
{
	_nsyy_state_type _nsyy_current_state;
	char *_nsyy_cp;
    
	_nsyy_current_state = (_nsyy_start);

	for ( _nsyy_cp = (_nsyytext_ptr) + _NSYY_MORE_ADJ; _nsyy_cp < (_nsyy_c_buf_p); ++_nsyy_cp )
		{
		_NSYY_CHAR _nsyy_c = (*_nsyy_cp ? _nsyy_ec[_NSYY_SC_TO_UI(*_nsyy_cp)] : 1);
		if ( _nsyy_accept[_nsyy_current_state] )
			{
			(_nsyy_last_accepting_state) = _nsyy_current_state;
			(_nsyy_last_accepting_cpos) = _nsyy_cp;
			}
		while ( _nsyy_chk[_nsyy_base[_nsyy_current_state] + _nsyy_c] != _nsyy_current_state )
			{
			_nsyy_current_state = (int) _nsyy_def[_nsyy_current_state];
			if ( _nsyy_current_state >= 59 )
				_nsyy_c = _nsyy_meta[_nsyy_c];
			}
		_nsyy_current_state = _nsyy_nxt[_nsyy_base[_nsyy_current_state] + _nsyy_c];
		}

	return _nsyy_current_state;
}

/* _nsyy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = _nsyy_try_NUL_trans( current_state );
 */
    static _nsyy_state_type _nsyy_try_NUL_trans  (_nsyy_state_type _nsyy_current_state )
{
	int _nsyy_is_jam;
    	char *_nsyy_cp = (_nsyy_c_buf_p);

	_NSYY_CHAR _nsyy_c = 1;
	if ( _nsyy_accept[_nsyy_current_state] )
		{
		(_nsyy_last_accepting_state) = _nsyy_current_state;
		(_nsyy_last_accepting_cpos) = _nsyy_cp;
		}
	while ( _nsyy_chk[_nsyy_base[_nsyy_current_state] + _nsyy_c] != _nsyy_current_state )
		{
		_nsyy_current_state = (int) _nsyy_def[_nsyy_current_state];
		if ( _nsyy_current_state >= 59 )
			_nsyy_c = _nsyy_meta[_nsyy_c];
		}
	_nsyy_current_state = _nsyy_nxt[_nsyy_base[_nsyy_current_state] + _nsyy_c];
	_nsyy_is_jam = (_nsyy_current_state == 58);

		return _nsyy_is_jam ? 0 : _nsyy_current_state;
}

#ifndef _NSYY_NO_UNPUT

#endif

#ifndef _NSYY_NO_INPUT
#ifdef __cplusplus
    static int _nsyyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(_nsyy_c_buf_p) = (_nsyy_hold_char);

	if ( *(_nsyy_c_buf_p) == _NSYY_END_OF_BUFFER_CHAR )
		{
		/* _nsyy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (_nsyy_c_buf_p) < &_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_ch_buf[(_nsyy_n_chars)] )
			/* This was really a NUL. */
			*(_nsyy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((_nsyy_c_buf_p) - (_nsyytext_ptr));
			++(_nsyy_c_buf_p);

			switch ( _nsyy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because _nsyy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					_nsyyrestart( _nsyyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( _nsyywrap(  ) )
						return 0;

					if ( ! (_nsyy_did_buffer_switch_on_eof) )
						_NSYY_NEW_FILE;
#ifdef __cplusplus
					return _nsyyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(_nsyy_c_buf_p) = (_nsyytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (_nsyy_c_buf_p);	/* cast for 8-bit char's */
	*(_nsyy_c_buf_p) = '\0';	/* preserve _nsyytext */
	(_nsyy_hold_char) = *++(_nsyy_c_buf_p);

	if ( c == '\n' )
		
    _nsyylineno++;
;

	return c;
}
#endif	/* ifndef _NSYY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void _nsyyrestart  (FILE * input_file )
{
    
	if ( ! _NSYY_CURRENT_BUFFER ){
        _nsyyensure_buffer_stack ();
		_NSYY_CURRENT_BUFFER_LVALUE =
            _nsyy_create_buffer( _nsyyin, _NSYY_BUF_SIZE );
	}

	_nsyy_init_buffer( _NSYY_CURRENT_BUFFER, input_file );
	_nsyy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void _nsyy_switch_to_buffer  (_NSYY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		_nsyypop_buffer_state();
	 *		_nsyypush_buffer_state(new_buffer);
     */
	_nsyyensure_buffer_stack ();
	if ( _NSYY_CURRENT_BUFFER == new_buffer )
		return;

	if ( _NSYY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(_nsyy_c_buf_p) = (_nsyy_hold_char);
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_pos = (_nsyy_c_buf_p);
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_n_chars = (_nsyy_n_chars);
		}

	_NSYY_CURRENT_BUFFER_LVALUE = new_buffer;
	_nsyy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (_nsyywrap()) processing, but the only time this flag
	 * is looked at is after _nsyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(_nsyy_did_buffer_switch_on_eof) = 1;
}

static void _nsyy_load_buffer_state  (void)
{
    	(_nsyy_n_chars) = _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_n_chars;
	(_nsyytext_ptr) = (_nsyy_c_buf_p) = _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_pos;
	_nsyyin = _NSYY_CURRENT_BUFFER_LVALUE->_nsyy_input_file;
	(_nsyy_hold_char) = *(_nsyy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c _NSYY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    _NSYY_BUFFER_STATE _nsyy_create_buffer  (FILE * file, int  size )
{
	_NSYY_BUFFER_STATE b;
    
	b = (_NSYY_BUFFER_STATE) _nsyyalloc( sizeof( struct _nsyy_buffer_state )  );
	if ( ! b )
		_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyy_create_buffer()" );

	b->_nsyy_buf_size = size;

	/* _nsyy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->_nsyy_ch_buf = (char *) _nsyyalloc( (_nsyy_size_t) (b->_nsyy_buf_size + 2)  );
	if ( ! b->_nsyy_ch_buf )
		_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyy_create_buffer()" );

	b->_nsyy_is_our_buffer = 1;

	_nsyy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with _nsyy_create_buffer()
 * 
 */
    void _nsyy_delete_buffer (_NSYY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == _NSYY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		_NSYY_CURRENT_BUFFER_LVALUE = (_NSYY_BUFFER_STATE) 0;

	if ( b->_nsyy_is_our_buffer )
		_nsyyfree( (void *) b->_nsyy_ch_buf  );

	_nsyyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a _nsyyrestart() or at EOF.
 */
    static void _nsyy_init_buffer  (_NSYY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	_nsyy_flush_buffer( b );

	b->_nsyy_input_file = file;
	b->_nsyy_fill_buffer = 1;

    /* If b is the current buffer, then _nsyy_init_buffer was _probably_
     * called from _nsyyrestart() or through _nsyy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != _NSYY_CURRENT_BUFFER){
        b->_nsyy_bs_lineno = 1;
        b->_nsyy_bs_column = 0;
    }

        b->_nsyy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, _NSYY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c _NSYY_CURRENT_BUFFER.
 * 
 */
    void _nsyy_flush_buffer (_NSYY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->_nsyy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->_nsyy_ch_buf[0] = _NSYY_END_OF_BUFFER_CHAR;
	b->_nsyy_ch_buf[1] = _NSYY_END_OF_BUFFER_CHAR;

	b->_nsyy_buf_pos = &b->_nsyy_ch_buf[0];

	b->_nsyy_at_bol = 1;
	b->_nsyy_buffer_status = _NSYY_BUFFER_NEW;

	if ( b == _NSYY_CURRENT_BUFFER )
		_nsyy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void _nsyypush_buffer_state (_NSYY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	_nsyyensure_buffer_stack();

	/* This block is copied from _nsyy_switch_to_buffer. */
	if ( _NSYY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(_nsyy_c_buf_p) = (_nsyy_hold_char);
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_buf_pos = (_nsyy_c_buf_p);
		_NSYY_CURRENT_BUFFER_LVALUE->_nsyy_n_chars = (_nsyy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (_NSYY_CURRENT_BUFFER)
		(_nsyy_buffer_stack_top)++;
	_NSYY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from _nsyy_switch_to_buffer. */
	_nsyy_load_buffer_state(  );
	(_nsyy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void _nsyypop_buffer_state (void)
{
    	if (!_NSYY_CURRENT_BUFFER)
		return;

	_nsyy_delete_buffer(_NSYY_CURRENT_BUFFER );
	_NSYY_CURRENT_BUFFER_LVALUE = NULL;
	if ((_nsyy_buffer_stack_top) > 0)
		--(_nsyy_buffer_stack_top);

	if (_NSYY_CURRENT_BUFFER) {
		_nsyy_load_buffer_state(  );
		(_nsyy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void _nsyyensure_buffer_stack (void)
{
	_nsyy_size_t num_to_alloc;
    
	if (!(_nsyy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(_nsyy_buffer_stack) = (struct _nsyy_buffer_state**)_nsyyalloc
								(num_to_alloc * sizeof(struct _nsyy_buffer_state*)
								);
		if ( ! (_nsyy_buffer_stack) )
			_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyyensure_buffer_stack()" );

		memset((_nsyy_buffer_stack), 0, num_to_alloc * sizeof(struct _nsyy_buffer_state*));

		(_nsyy_buffer_stack_max) = num_to_alloc;
		(_nsyy_buffer_stack_top) = 0;
		return;
	}

	if ((_nsyy_buffer_stack_top) >= ((_nsyy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		_nsyy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (_nsyy_buffer_stack_max) + grow_size;
		(_nsyy_buffer_stack) = (struct _nsyy_buffer_state**)_nsyyrealloc
								((_nsyy_buffer_stack),
								num_to_alloc * sizeof(struct _nsyy_buffer_state*)
								);
		if ( ! (_nsyy_buffer_stack) )
			_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((_nsyy_buffer_stack) + (_nsyy_buffer_stack_max), 0, grow_size * sizeof(struct _nsyy_buffer_state*));
		(_nsyy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
_NSYY_BUFFER_STATE _nsyy_scan_buffer  (char * base, _nsyy_size_t  size )
{
	_NSYY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != _NSYY_END_OF_BUFFER_CHAR ||
	     base[size-1] != _NSYY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (_NSYY_BUFFER_STATE) _nsyyalloc( sizeof( struct _nsyy_buffer_state )  );
	if ( ! b )
		_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyy_scan_buffer()" );

	b->_nsyy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->_nsyy_buf_pos = b->_nsyy_ch_buf = base;
	b->_nsyy_is_our_buffer = 0;
	b->_nsyy_input_file = NULL;
	b->_nsyy_n_chars = b->_nsyy_buf_size;
	b->_nsyy_is_interactive = 0;
	b->_nsyy_at_bol = 1;
	b->_nsyy_fill_buffer = 0;
	b->_nsyy_buffer_status = _NSYY_BUFFER_NEW;

	_nsyy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to _nsyylex() will
 * scan from a @e copy of @a str.
 * @param _nsyystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       _nsyy_scan_bytes() instead.
 */
_NSYY_BUFFER_STATE _nsyy_scan_string (const char * _nsyystr )
{
    
	return _nsyy_scan_bytes( _nsyystr, (int) strlen(_nsyystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to _nsyylex() will
 * scan from a @e copy of @a bytes.
 * @param _nsyybytes the byte buffer to scan
 * @param __nsyybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
_NSYY_BUFFER_STATE _nsyy_scan_bytes  (const char * _nsyybytes, int  __nsyybytes_len )
{
	_NSYY_BUFFER_STATE b;
	char *buf;
	_nsyy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (_nsyy_size_t) (__nsyybytes_len + 2);
	buf = (char *) _nsyyalloc( n  );
	if ( ! buf )
		_NSYY_FATAL_ERROR( "out of dynamic memory in _nsyy_scan_bytes()" );

	for ( i = 0; i < __nsyybytes_len; ++i )
		buf[i] = _nsyybytes[i];

	buf[__nsyybytes_len] = buf[__nsyybytes_len+1] = _NSYY_END_OF_BUFFER_CHAR;

	b = _nsyy_scan_buffer( buf, n );
	if ( ! b )
		_NSYY_FATAL_ERROR( "bad buffer in _nsyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->_nsyy_is_our_buffer = 1;

	return b;
}

#ifndef _NSYY_EXIT_FAILURE
#define _NSYY_EXIT_FAILURE 2
#endif

static void _nsyynoreturn _nsyy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( _NSYY_EXIT_FAILURE );
}

/* Redefine _nsyyless() so it works in section 3 code. */

#undef _nsyyless
#define _nsyyless(n) \
	do \
		{ \
		/* Undo effects of setting up _nsyytext. */ \
        int _nsyyless_macro_arg = (n); \
        _NSYY_LESS_LINENO(_nsyyless_macro_arg);\
		_nsyytext[_nsyyleng] = (_nsyy_hold_char); \
		(_nsyy_c_buf_p) = _nsyytext + _nsyyless_macro_arg; \
		(_nsyy_hold_char) = *(_nsyy_c_buf_p); \
		*(_nsyy_c_buf_p) = '\0'; \
		_nsyyleng = _nsyyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int _nsyyget_lineno  (void)
{
    
    return _nsyylineno;
}

/** Get the input stream.
 * 
 */
FILE *_nsyyget_in  (void)
{
        return _nsyyin;
}

/** Get the output stream.
 * 
 */
FILE *_nsyyget_out  (void)
{
        return _nsyyout;
}

/** Get the length of the current token.
 * 
 */
int _nsyyget_leng  (void)
{
        return _nsyyleng;
}

/** Get the current token.
 * 
 */

char *_nsyyget_text  (void)
{
        return _nsyytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void _nsyyset_lineno (int  _line_number )
{
    
    _nsyylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see _nsyy_switch_to_buffer
 */
void _nsyyset_in (FILE *  _in_str )
{
        _nsyyin = _in_str ;
}

void _nsyyset_out (FILE *  _out_str )
{
        _nsyyout = _out_str ;
}

int _nsyyget_debug  (void)
{
        return _nsyy_flex_debug;
}

void _nsyyset_debug (int  _bdebug )
{
        _nsyy_flex_debug = _bdebug ;
}

static int _nsyy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from _nsyylex_destroy(), so don't allocate here.
     */

    /* We do not touch _nsyylineno unless the option is enabled. */
    _nsyylineno =  1;
    
    (_nsyy_buffer_stack) = NULL;
    (_nsyy_buffer_stack_top) = 0;
    (_nsyy_buffer_stack_max) = 0;
    (_nsyy_c_buf_p) = NULL;
    (_nsyy_init) = 0;
    (_nsyy_start) = 0;

/* Defined in main.c */
#ifdef _NSYY_STDINIT
    _nsyyin = stdin;
    _nsyyout = stdout;
#else
    _nsyyin = NULL;
    _nsyyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * _nsyylex_init()
     */
    return 0;
}

/* _nsyylex_destroy is for both reentrant and non-reentrant scanners. */
int _nsyylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(_NSYY_CURRENT_BUFFER){
		_nsyy_delete_buffer( _NSYY_CURRENT_BUFFER  );
		_NSYY_CURRENT_BUFFER_LVALUE = NULL;
		_nsyypop_buffer_state();
	}

	/* Destroy the stack itself. */
	_nsyyfree((_nsyy_buffer_stack) );
	(_nsyy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * _nsyylex() is called, initialization will occur. */
    _nsyy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef _nsyytext_ptr
static void _nsyy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef _NSYY_NEED_STRLEN
static int _nsyy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *_nsyyalloc (_nsyy_size_t  size )
{
			return malloc(size);
}

void *_nsyyrealloc  (void * ptr, _nsyy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void _nsyyfree (void * ptr )
{
			free( (char *) ptr );	/* see _nsyyrealloc() for (char *) cast */
}

#define _NSYYTABLES_NAME "_nsyytables"

#line 95 "/home/marven/Git/cheviot/bsdutils/lib/nslexer.l"


#undef _ns_nsyywrap
int
_ns_nsyywrap(void)
{
	return 1;
} /* _ns_nsyywrap */

void
_ns_nsyyerror(const char *msg)
{

	 log_warn("libc nsdispatch: %s line %d: %s at '%s'",
	    _PATH_NS_CONF, _nsyylineno, msg, _nsyytext);
} /* _ns_nsyyerror */

